# Uncomment the next line to define a global platform for your project
 #platform :ios, '9.0'

target 'testCocoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for testCocoa
  pod 'Alamofire', '5.4.2'

  target 'testCocoaTests' do
    # Pods for testing
  end

end
